### ISSUE TITLE
how can i upload photo?

### ISSUE THREAD

**Issue by mayajuni** [terikon/cordova-plugin-photo-library#45] opened 2017-03-21 02:08 UTC
hi. thank you for your plugin. 

i hava problum.

i used this and transfer plugins. i want to upload photo. 

I tried it several times with the photoURL.

how can i used photoURL and upload file??

**Comment by Kanaho** [comment] 2017-03-21 09:44
I'm facing the same problem. I can't upload my pics with fileTransfer.
And the getter of base64 keep returning me undefined.

Help will be very apprecied.
And thanks for the plugins.

**Comment by Kanaho** [comment] 2017-03-21 10:31
Well resolved for me, was just a bug on my server side who limited the size of files.

`var options = {
            fileKey: "qqfile",
            fileName: filename,
            mimeType: "image/jpeg"
        };

        const fileTransfer = new Transfer();

        return fileTransfer.upload(filename, url, options)`

That should make the job mayajuni

**Comment by mayajuni** [comment] 2017-03-22 07:00
@Kanaho 
thank you for your answer.

i tried your code. but i can not it. 

i have error.

`
FileTransferError
body: null
code: 1
exception: null
http_status: null
source: "D5A11FF0-80BE-4236-BA19-62CA7D51D0EC.JPG"
`
what is filename? libraryItem.fileName?

thanks.

**Comment by mayajuni** [comment] 2017-03-22 07:16
this error is 'FileTransferError.FILE_NOT_FOUND_ERR'

i think, i need file path(dateURL or fileURL). 

how can i get?

**Comment by Kanaho** [comment] 2017-03-22 11:24
No, my "filename" is a variable who get libraryItem.photoURL.
But you're right in the fact that the name is not really well choose, that's more the full path that you have to give to the FileTransfer, and he accept the cdvphotolibrary format so that work pretty fine.

**Comment by mayajuni** [comment] 2017-03-23 01:24
@Kanaho 
Thank you for replay.
I also tried it. but same error.
do you test ios?
what do you use file transfer plugin?

**Comment by Kanaho** [comment] 2017-03-30 12:29
Finally tried on IOS and yeay, i've the same error than you. It only work on Android
I think that's because this plugin don't return a .jpg in the fileUrl (photo or thumbnail) and file-transfer dont find a file without any type.

**Comment by viskin** [comment] 2017-04-11 11:30
Duplicate of #51 - let's move the conversation there

**Closed by viskin** 2017-04-11 11:30 UTC
